### ISSUE TITLE
Please extract XDR library

### ISSUE THREAD

**Issue by cblp** [dylex/haskell-nfs#1]
I want to use it in Stellar API implementation

**Comment by dylex** [comment]
You should be able to use all the XDR stuff from the rpc library as-is.  The reason it's packaged together with the network interface is to provide a fully functional `rpcgen` interface, but there's no reason you need to use the network pieces if you just want xdr encoding/decoding.  Or maybe I'm missing something.  (It's been quite a while since I looked at any of this, but I have now at least updated it for lts-18.)

**Comment by cblp** [comment]
Yes, I use it now with ONC, but I don't need network, and for me it may be easier to send patches without network. And rpcgen doesn't depend on ONC.

Okay, for now, I think, there is no problem in extra ONC parts.
